# class map supported by the pipeline
class_maps_supported = {
    1: "adrenal_gland_left",
    2: "adrenal_gland_right",
    3: "aorta",
    4: "bladder",
    5: "celiac_artery",
    6: "colon",
    7: "common_bile_duct",
    8: "duodenum",
    9: "femur_left",
    10: "femur_right",
    11: "gall_bladder",
    12: "kidney_left",
    13: "kidney_right",
    14: "liver",
    15: "lung_left",
    16: "lung_right",
    17: "pancreas",
    18: "pancreas_body",
    19: "pancreas_head",
    20: "pancreas_tail",
    21: "pancreatic_duct",
    22: "postcava",
    23: "prostate",
    24: "spleen",
    25: "stomach",
    26: "superior_mesenteric_artery",
    27: "veins",
    ###### new classes ######
    # 28: "celiac_trunk",
    29: "esophagus",
    # 30: "hepatic_vessel",
    31: "intestine",
    # 32: "portal_vein_and_splenic_vein",
    # 33: "rectum",
}
